context("restopt_problem")

test_that("create_problem", {
  habitat <- terra::rast(system.file("extdata", "habitat.tif", package = "restoptr"))
  restorable <- terra::rast(system.file("extdata", "restorable.tif", package = "restoptr"))
  accessible <- terra::rast(system.file("extdata", "accessible.tif", package = "restoptr"))
  problem <- RestoptProblem(habitat=habitat, restorable=restorable, accessible=accessible)
  testthat::expect_equal(problem@habitat_path, terra::sources(habitat)[[1]])
  testthat::expect_equal(problem@restorable_path, terra::sources(restorable)[[1]])
  testthat::expect_equal(problem@accessible_path, terra::sources(accessible)[[1]])
  testthat::expect_false(hasNbComponentsConstraint(problem))
  testthat::expect_false(hasCompactnessConstraint(problem))
  testthat::expect_false(hasRestorableConstraint(problem))
  problem <- postNbComponentsConstraint(problem, 1, 1)
  testthat::expect_true(hasNbComponentsConstraint(problem))
  problem <- postRestorableConstraint(problem, 90, 110, 23, 0.7)
  testthat::expect_true(hasRestorableConstraint(problem))
  problem <- postCompactnessConstraint(problem, 6)
  testthat::expect_true(hasCompactnessConstraint(problem))
})
